name: 'Run E2E Tests'
description: "Runs Adyen Shopware E2E Tests"


inputs:
  SHOPWARE:
    description: "The Shopware version that is used to run the tests."
    required: true
  PHP:
    description: "The PHP Version that is used for the Shopware container."
    required: true
  MOLLIE_APIKEY_TEST:
    description: "The Mollie Test API key. Required for the installation."
    default: ''
    required: true

  _SHOP_DOMAIN:
    description: 'This domain will be used in Cypress as BASE_URL'
    default: 'adyen.shopware'
    required: false
  _ZIP_FILE:
    description: 'This is the defined filename of the ZIP file that we use for the installation of the plugin'
    default: '~/.build/AdyenPayment.zip'
    required: false



runs:
  using: "composite"
  steps:

    - name: Download Docker
      shell: bash
      run: docker pull -q dockware/play:${{ inputs.SHOPWARE }}

    - name: Start Docker
      shell: bash
      run: |
        docker run -p 80:80 --name shop --env PHP_VERSION=${{ inputs.PHP }} -d dockware/play:${{ inputs.SHOPWARE }}
        sleep 30
        # now change the domain of our shop
        sudo echo "127.0.0.1 ${{ inputs._SHOP_DOMAIN }}" | sudo tee -a /etc/hosts
        docker exec shop bash -c "mysql -h 127.0.0.1 -u root -proot shopware -e \"UPDATE s_core_shops SET host = '${{ inputs._SHOP_DOMAIN }}', hosts = '', secure = 0;\""

    - name: Upload ZIP File to Docker
      shell: bash
      run: |
        docker cp ${{ inputs._ZIP_FILE }} shop:/var/www/html/custom/plugins/AdyenPayment.zip
        docker exec shop bash -c 'cd /var/www/html/custom/plugins && unzip -qq -o AdyenPayment.zip'

    - name: Install Plugin
      shell: bash
      run: |
        docker exec shop bash -c 'php bin/console sw:plugin:refresh'
        docker exec shop bash -c 'php bin/console sw:plugin:install --activate AdyenPayment'
        docker exec shop bash -c 'php bin/console sw:cache:clear'