image: docphpro/php:7.4-dev

pipelines:
    default:
        - step:
              name: Quality Assurance
              caches:
                  - composer
              script:
                  - echo "memory_limit=-1" >> /usr/local/etc/php/php.ini
                  - composer install --prefer-dist
                  - composer install --prefer-dist -d ./tools/
                  - php ./vendor/bin/grumphp run

    branches:
        master:
            - step:
                  name: Code Compatibility
                  caches:
                      - composer
                  script:
                      - echo "memory_limit=-1" >> /usr/local/etc/php/php.ini
                      - composer install --prefer-dist
                      - php ./vendor/bin/grumphp run --testsuite="code-compatibility"
