image: docphpro/php:7.4-dev

definitions:
    steps:
        - step: &setup
            name: Continues Integration Setup
            caches:
              - composer
            script:
              - echo "memory_limit=-1" >> /usr/local/etc/php/php.ini
              - composer install --prefer-dist

pipelines:
    default:
        - step: *setup
        - step:
              name: Quality Assurance
              script:
                  - php ./vendor/bin/grumphp run

    branches:
        master:
            - step: *setup
            - step:
                  name: Compatibility
                  script:
                      - php ./vendor/bin/grumphp run --testsuite=master
