name: 'Build Plugin'
description: "Builds the Plugin"
runs:
  using: "composite"
  steps:
    - name: Change access rights
      shell: bash
      run: sudo chmod 777 -R ./tools
    - name: Build plugin
      shell: bash
      run: ./tools/deploy.sh
    - name: Copy to build cache
      shell: bash
      run: cp -R ./tools/AdyenPayment.zip ~/.build
    - name: Store ZIP file in Github
      uses: actions/upload-artifact@v2
      with:
        name: AdyenPayment-Shopware
        retention-days: 4
        path: ~/.build