name: 'Build Plugin'
description: "Builds the Plugin"

inputs:
  shopware:
    description: "The Shopware version that is used to build the plugin"
    required: true
runs:
  using: "composite"
  steps:
    - name: Change access rights
      shell: bash
      run: sudo chmod 777 -R ./tools
    - name: Build plugin
      shell: bash
      run: ./tools/deploy.sh
    - name: Copy to build cache
      shell: bash
      run: cp -R ./tools ~/.build
    - name: Store ZIP file in Github
      uses: actions/upload-artifact@v2
      with:
        name: AdyenPayment-Shopware-${{ inputs.shopware }}
        retention-days: 4
        path: ~/.build