name: CI Pipeline Shopware 5
on:
  push:
    branches:
      - feature/main_e2e_tests
jobs:
  build:
    permissions:
      contents: read
      pages: write
      id-token: write
    name: Build environment
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Create Cache Directories
        run: |
          mkdir -p ~/.build
      - name: Mount Build Cache
        uses: actions/cache@v3
        with:
          key: cache-plugin-${{ github.run_id }}
          path: ~/.build
      - name: Build Plugin
        uses: ./.github/actions/build_plugin
  
  run:
    name: E2E | Shopware ${{ matrix.shopware }}, PHP ${{ matrix.php }}, Browser ${{matrix.browser}}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - shopware: '5.6.10'
            php: '7.4'
            port: 443
            browser: 'chromium'
            device: 'Desktop Chrome'
          - shopware: '5.7.18'
            php: '7.4'
            port: 443
            browser: 'firefox'
            device: 'Desktop Firefox'
          - shopware: '5.7.8'
            php: '8.1'
            port: 443
            browser: 'chromium'
            device: 'Desktop Chrome'
#
#          - shopware: '5.6.10'
#            php: '7.4'
#            port: 443
#            browser: 'firefox'
#            device: 'Desktop Firefox'
#          - shopware: '5.7.18'
#            php: '7.4'
#            port: 443
#            browser: 'firefox'
#            device: 'Desktop Firefox'
#          - shopware: '5.7.8'
#            php: '8.1'
#            port: 443
#            browser: 'firefox'
#            device: 'Desktop Firefox'
    steps:
      - name: Clone Code
        uses: actions/checkout@v3
        with:
          path: main

      - name: Mount Build Cache
        uses: actions/cache@v3
        with:
          key: cache-plugin-${{ github.run_id }}
          path: ~/.build


      - name: E2E Tests, Shopware ${{ matrix.shopware }}
        uses: ./main/.github/actions/run_e2e
        with:
          SHOPWARE: ${{ matrix.shopware }}
          PHP: ${{ matrix.php }}
          NODE: 20
          PORT: ${{ matrix.port }}
          NGROK: ${{ secrets.NGROK }}
          GH_PAT: ${{ secrets.GH_PAT }}
          API_KEY_TEST: ${{ secrets.API_KEY_TEST }}
          API_KEY_LIVE: ${{ secrets.API_KEY_LIVE }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          SHOPWARE_TEST_REPO: ${{secrets.SHOPWARE_TEST_REPO}}
          COMMON_TEST_REPO: ${{secrets.COMMON_TEST_REPO}}
          PAY_PAL_EMAIL: ${{secrets.PAY_PAL_EMAIL}}
          PAY_PAL_PASSWORD: ${{secrets.PAY_PAL_PASSWORD}}
          BROWSER: ${{ matrix.browser }}
          DEVICE: ${{ matrix.device }}
          